import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ka';

interface Translations {
  [key: string]: any;
}

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      services: 'Services',
      methodology: 'Methodology',
      whyAi: 'Why AI?',
      cta: 'Schedule a private meeting',
      ctaMobile: 'Schedule Meeting',
      servicesLink: 'Services',
      contactLink: 'Contact',
      privacyLink: 'Privacy Policy',
      copyright: '© 2025 TimeVault Inc. Save your time in the safe space.'
    },
    hero: {
      bgText: 'TIMEVAULT',
      titleLine1: 'The Gap Is Widening',
      titleLine2: 'Be on the right side of history',
      description: 'We are living through the biggest shift since the internet. TimeVault leverages the power of artificial intelligence to build websites, generate content, and automate your entire workflow.',
      cta: 'Explore Solutions',
      stats: {
        saveHours: 'Save Hours everyday',
        increaseRoi: 'Increase ROI',
        boostAwareness: 'Boost Awareness',
        pullAway: 'Pull Away from Competition'
      }
    },
    tools: {
      headline: 'Comprehensive Digital',
      headlineHighlight: 'Acceleration',
      buttons: {
        web: 'Web Architecture',
        content: 'AI Marketing',
        auto: 'Business Automation'
      },
      featured: 'Featured Service',
      exploreBtn: 'Explore',
      content: {
        web: {
          title: "High-Tech Web Architecture",
          description: "Google-optimized SEO, dynamic visuals, and easily updatable infrastructure for your business's digital growth.",
          exploreLabel: "More about Web Architecture"
        },
        auto: {
          title: "Business Process Automation",
          description: "Full automation of CRM systems, documentation, and digital infrastructure, freeing up your time for what matters most.",
          exploreLabel: "More about Business Automation"
        },
        content: {
          title: "AI Marketing Autopilot",
          description: "Automated posts, photorealistic visuals, and content strategies tailored to modern trends.",
          exploreLabel: "More about AI Marketing"
        }
      }
    },
    home: {
      rocket: {
        ready: "READY FOR TAKEOFF"
      },
      methodology: {
        badge: "METHODOLOGY",
        title: "Innovation",
        titleHighlight: "Without Risk",
        subtitle: "Save your time in the safe space.",
        description: "Technology is moving fast. Businesses that ignore these tools are becoming obsolete. TimeVault acts as your secure bridge to the future—providing the safety of a managed service with the explosive power of modern AI."
      }
    },
    showcase: {
      tag: "The Visual Turing Test",
      titleLine1: "Don't believe in the",
      titleLine2: "Power of AI?",
      desc: "Many business owners believe AI content still looks robotic or fake. We challenge you to a quick 3-question test. Can your eye distinguish reality from code?",
      cta: "Take the One-Minute Test",
      playing: {
        instruction: "Click the image you think is AI-generated.",
        q1: "Round 1: Select the AI-generated portrait.",
        q2: "Round 2: Which product shot is synthetic?",
        q3: "Round 3: Which interior design never existed?",
        hover: "Pick This One"
      },
      results: {
        tag: "Test Results",
        accuracy: "Total Accuracy",
        messagePart1: "\"Technically, you were right. But the truth is, ",
        messageHighlight: "every single image",
        messagePart2: " you just saw in this test was generated by AI.\"",
        rightSideTitle1: "The Uncanny Valley",
        rightSideTitle2: "Has Been Bridged.",
        rightSideP1: "The bottleneck of quality no longer exists. The era where AI content looked \"fake\" is over. Today, we can generate hyper-realistic assets for your brand at a fraction of the cost and 100x the speed of traditional production.",
        rightSideP2: "This is not just a parlor trick—it is the new economic reality. Businesses that integrate these capabilities now will define the market standards of tomorrow.",
        restart: "Review Images Again"
      }
    },
    footer: {
      brandDesc: "Empowering brands to master time and unlock wealth through intelligent AI automation and high-end design.",
      strategyTitle: "Signature Strategy",
      strategyHighlight: "Engineered for Performance",
      strategyDesc: "Move past standard industry practices. We architect custom frameworks that transform bottlenecks into competitive advantages.",
      ctaButton: "Schedule a Private Meeting",
      ctaSub: "Free Strategy Audit • No Commitment"
    },
    servicePage: {
      backHome: "Back to Home",
      whyChoose: "Why Choose TimeVault?",
      schedule: "Schedule Consultation",
      riskFree: "Risk Free • No Commitment",
      keyCapabilities: "Key Capabilities",
      services: {
        web: {
          title: "Web Architecture",
          subtitle: "SEO Optimized Websites",
          description: [
            "In the era of Artificial Intelligence, web technologies have no limits. With AI capabilities, we can create any design and functionality a person can imagine. Whether it's complex animation or a unique system, our technology makes it a reality.",
            "SEO (Search Engine Optimization) is what makes your business visible on the internet. When a user searches for your service, your site should appear first. We ensure your digital product is technically sound and understandable for search engines, directly impacting your revenue."
          ],
          benefits: [
            "Dynamic SEO",
            "Premium Brand Visuals",
            "Full Content Control",
            "Maximum Speed & Security"
          ],
          features: [
            { title: "Google Optimized SEO", desc: "Technical optimization ensuring top positions in Google search results." },
            { title: "Dynamic Visuals", desc: "Interactive elements that increase brand value in the eyes of the user." },
            { title: "Easily Updatable Infrastructure", desc: "A website whose visuals can be updated by any client." }
          ]
        },
        content: {
          title: "AI Marketing",
          subtitle: "Infinite Creativity, Zero Burnout",
          description: [
            "Content is a crucial factor for maintaining brand relevance, but as we know, creating it requires immense time and energy. Our models take the best details from successful international marketing campaigns and use this knowledge to create your content. Additionally, our technology ensures the generation of high-quality visuals, eliminating the need for expensive photoshoots.",
            "We create individual systems that combine global experience with your brand's unique voice. This ensures every piece of content is world-class and fully compliant with modern standards, yet created 100x faster."
          ],
          benefits: [
            "Savings on Time, Money & Energy",
            "Continuous Social Activity",
            "Quick Trend Adoption",
            "World-Class Brand Consistency"
          ],
          features: [
            { title: "Posts & Blogs Autopilot", desc: "Automatic preparation and publishing of text materials for social networks and websites." },
            { title: "High-Quality Product Visuals", desc: "Creating photorealistic visuals from home that are indistinguishable from reality." },
            { title: "Constant Ideas for Trend-Driven Content", desc: "Global trend analysis and constant delivery of new ideas tailored to your brand." }
          ]
        },
        auto: {
          title: "Business Automation",
          subtitle: "The Invisible Workflow",
          description: [
            "If you perform an action several times a year or more often, chances are its automation is possible through AI. Establishing contact with customers, creating documents and extracting information, company internal information exchange, and digital infrastructure cleanup...",
            "In these and many other matters, Artificial Intelligence can save you hours daily to use on much more important things. Our systems take full responsibility for these routine processes, allowing you to focus on much more important, strategic goals and increase business efficiency."
          ],
          benefits: [
            "Save Hours of Daily Work",
            "CRM Automation",
            "Documentation Automation",
            "Error-Proof Systems"
          ],
          features: [
            { title: "CRM Automation", desc: "Full automation of customer data management and sales processes to increase efficiency." },
            { title: "Document Creation & Info Extraction", desc: "Documentation generation and automatic processing of required text data from files." },
            { title: "Digital Infrastructure Automation", desc: "Creating a unified, automated ecosystem of company internal systems and tools." }
          ]
        }
      }
    }
  },
  ka: {
    nav: {
      services: 'სერვისები',
      methodology: 'მეთოდოლოგია',
      whyAi: 'რატომ AI?',
      cta: 'პირადი შეხვედრის დაჯავშნა',
      ctaMobile: 'შეხვედრის დაჯავშნა',
      servicesLink: 'სერვისები',
      contactLink: 'კონტაქტი',
      privacyLink: 'კონფიდენციალურობა',
      copyright: '© 2025 TimeVault Inc. დაზოგეთ დრო უსაფრთხო სივრცეში.'
    },
    hero: {
      bgText: 'TIMEVAULT',
      titleLine1: 'ჩამორჩენა იზრდება',
      titleLine2: 'დადექით ისტორიის სწორ მხარეს',
      description: 'ჩვენ ვცხოვრობთ ყველაზე დიდი ცვლილების ეპოქაში ინტერნეტის შექმნის შემდეგ. TimeVault იყენებს ხელოვნური ინტელექტის ძალას ვებ-გვერდების შესაქმნელად, კონტენტის გენერირებისთვის და თქვენი სამუშაო პროცესის სრული ავტომატიზაციისთვის.',
      cta: 'გაეცანით სერვისებს',
      stats: {
        saveHours: 'დაზოგეთ საათები ყოველდღიურად',
        increaseRoi: 'გაზარდეთ ROI',
        boostAwareness: 'გაზარდეთ ცნობადობა',
        pullAway: 'გაუსწარით კონკურენციას'
      }
    },
    tools: {
      headline: 'ციფრული პროცესების',
      headlineHighlight: 'აქსელერაცია',
      buttons: {
        web: 'ვებ არქიტექტურა',
        content: 'AI მარკეტინგი',
        auto: 'ბიზნეს ავტომატიზაცია'
      },
      featured: 'რჩეული სერვისი',
      exploreBtn: 'აღმოაჩინე',
      content: {
        web: {
          title: "მაღალტექნოლოგიური ვებ-არქიტექტურა",
          description: "Google-ის საძიებო სისტემაზე მორგებული SEO, დინამიური ვიზუალები და მარტივად განახლებადი ინფრასტრუქტურა თქვენი ბიზნესის ციფრული ზრდისთვის.",
          exploreLabel: "მეტი ვებ-არქიტექტურის შესახებ"
        },
        auto: {
          title: "ბიზნეს პროცესების ავტომატიზაცია",
          description: "CRM სისტემების, დოკუმენტაციის მომზადებისა და ციფრული ინფრასტრუქტურის სრული ავტომატიზაცია, რაც გიონთავისუფლებთ დროს მნიშვნელოვანი საქმეებისთვის.",
          exploreLabel: "მეტი ბიზნეს-ავტომატიზაციის შესახებ"
        },
        content: {
          title: "AI მარკეტინგული ავტოპილოტი",
          description: "ავტომატიზირებული პოსტები, ფოტორეალისტური ვიზუალები და თანამედროვე ტრენდებზე მორგებული კონტენტ-სტრატეგია.",
          exploreLabel: "მეტი AI-მარკეტინგის შესახებ"
        }
      }
    },
    home: {
      rocket: {
        ready: "მზად ვართ აფრენისთვის"
      },
      methodology: {
        badge: "მეთოდოლოგია",
        title: "ინოვაცია",
        titleHighlight: "რისკის გარეშე",
        subtitle: "დაზოგეთ დრო უსაფრთხო სივრცეში.",
        description: "მოძველებული მეთოდებით მუშაობა არაეფექტური და ძვირია. TimeVault-ი ამ პროცესებს სრულიად ცვლის. ჩვენი ტექნოლოგიებით დავალებები ბევრად სწრაფად სრულდება, რაც საშუალებას გვაძლევს, ვიყოთ უფრო ეფექტურები და ჩვენი სერვისი თქვენთვის უფრო ხელმისაწვდომი გავხადოთ. ნაკლები დრო ოპერაციებზე ნიშნავს მეტ დანაზოგს თქვენი ბიზნესისთვის."
      }
    },
    showcase: {
      tag: "ვიზუალური ტიურინგის ტესტი",
      titleLine1: "არ გჯერათ",
      titleLine2: "AI-ის ძალის?",
      desc: "ბევრ ბიზნეს მფლობელს ჰგონია, რომ AI კონტენტი კვლავ რობოტულად ან ყალბად გამოიყურება. ჩვენ გიწვევთ სწრაფ 3-კითხვიან ტესტზე. შეუძლია თქვენს თვალს გაარჩიოს რეალობა კოდისგან?",
      cta: "გაიარეთ ერთწუთიანი ტესტი",
      playing: {
        instruction: "დააჭირეთ ფოტოს, რომელიც თქვენი აზრით AI-ის შექმნილია.",
        q1: "რაუნდი 1: აირჩიეთ AI-ის მიერ შექმნილი პორტრეტი.",
        q2: "რაუნდი 2: რომელი პროდუქტის ფოტოა სინთეტიკური?",
        q3: "რაუნდი 3: რომელი ინტერიერის დიზაინი არ არსებობდა არასდროს?",
        hover: "აირჩიე ეს"
      },
      results: {
        tag: "ტესტის შედეგები",
        accuracy: "სრული სიზუსტე",
        messagePart1: "\"ტექნიკურად, თქვენ მართალი იყავით. მაგრამ სიმართლე ის არის, რომ ",
        messageHighlight: "თითოეული სურათი",
        messagePart2: ", რომელიც ახლა ნახეთ, AI-ის მიერ იყო გენერირებული.\"",
        rightSideTitle1: "ზღვარი რეალობასა და",
        rightSideTitle2: "გამოგონილს შორის წაიშალა.",
        rightSideP1: "ხარისხის პრობლემა აღარ არსებობს. ეპოქა, როდესაც AI კონტენტი \"ყალბად\" გამოიყურებოდა, დასრულდა. დღეს ჩვენ შეგვიძლია შევქმნათ ჰიპერ-რეალისტური მასალები თქვენი ბრენდისთვის ტრადიციული წარმოების ღირებულების მცირე ნაწილად და 100-ჯერ უფრო სწრაფად.",
        rightSideP2: "ეს არ არის უბრალო გასართობი ტრიუკი — ეს ახალი ეკონომიკური რეალობაა. ბიზნესები, რომლებიც ამ შესაძლებლობებს ახლა დანერგავენ, განსაზღვრავენ ხვალინდელი ბაზრის სტანდარტებს.",
        restart: "სურათების ხელახლა ნახვა"
      }
    },
    footer: {
      brandDesc: "ბრენდების გაძლიერება მარკეტინგული აქტივების შექმნითა და შიდა პროცესების ავტომატიზაციის საშუალებით, დროისა და თანხის დაზოგვის თანხლებით.",
      strategyTitle: "უნიკალური სტრატეგია",
      strategyHighlight: "შექმნილია შედეგისთვის",
      strategyDesc: "გასცდით სტანდარტულ ინდუსტრიულ პრაქტიკას. ჩვენ ვქმნით ინდივიდუალურ სისტემებს, რომლებიც შეფერხებებს კონკურენტულ უპირატესობად აქცევს.",
      ctaButton: "პირადი შეხვედრის დაჯავშნა",
      ctaSub: "უფასო სტრატეგიული აუდიტი • ვალდებულებების გარეშე"
    },
    servicePage: {
      backHome: "მთავარზე დაბრუნება",
      whyChoose: "რატომ TimeVault?",
      schedule: "კონსულტაციის დაჯავშნა",
      riskFree: "რისკის გარეშე • ვალდებულებების გარეშე",
      keyCapabilities: "ძირითადი შესაძლებლობები",
      services: {
        web: {
          title: "ვებ არქიტექტურა",
          subtitle: "SEO ოფტიმიზირებული ვებსაიტები",
          description: [
            "ხელოვნური ინტელექტის ეპოქაში ვებ-ტექნოლოგიებს საზღვრები არ აქვს. AI-ს შესაძლებლობებით ჩვენ შეგვიძლია შევქმნათ ნებისმიერი დიზაინი და ფუნქციონალი, რომელსაც ადამიანი წარმოიდგენს. იქნება ეს რთული ანიმაცია თუ უნიკალური სისტემა, ჩვენი ტექნოლოგია მას რეალობად აქცევს.",
            "SEO (საძიებო სისტემების ოპტიმიზაცია) არის ის, რაც თქვენს ბიზნესს ინტერნეტში ხილვადს ხდის. როდესაც მომხმარებელი ეძებს თქვენს სერვისს, თქვენი საიტი პირველი უნდა გამოჩნდეს. ჩვენ უზრუნველვყოფთ, რომ თქვენი ციფრული პროდუქტი იყოს ტექნიკურად გამართული და გასაგები საძიებო სისტემებისთვის, რაც პირდაპირ აისახება თქვენს შემოსავალზე."
          ],
          benefits: [
            "დინამიური SEO",
            "ბრენდის პრემიუმ ვიზუალი",
            "სრული კონტროლი კონტენტზე",
            "მაქსიმალური სისწრაფე და დაცულობა"
          ],
          features: [
            { title: "Google-ის საძიებო სისტემაზე მორგებული SEO", desc: "ტექნიკური ოპტიმიზაცია, რომელიც უზრუნველყოფს ვებსაიტის მოწინავე პოზიციებს Google-ის ძიების შედეგებში." },
            { title: "დინამიური ვიზუალები", desc: "ინტერაქტიული ელემენტები, რომლებიც ზრდის ბრენდის ღირებულებას მომხმარებლის თვალში." },
            { title: "მარტივად განახლებადი ინფრასტრუქტურა", desc: "ვებსაიტი, რომლის ვიზუალების განახლებაც ნებისმიერ კლიენტს შეეძლება." }
          ]
        },
        content: {
          title: "AI მარკეტინგი",
          subtitle: "უსაზღვრო კრეატიულობა, გადაწვის გარეშე",
          description: [
            "კონტენტი უმნიშვნელოვანესი ფაქტორია ბრენდის რელევანტურობის შესანარჩუნებლად, თუმცა როგორც მოგვეხსენება, მისი დამზადება უდიდეს დროსა და ენერგიას მოითხოვს. ჩვენი მოდელები იღებენ საუკეთესო დეტალებს წარმატებული საერთაშორისო მარკეტინგული კამპანიებიდან და იყენებენ ამ ცოდნას თქვენი კონტენტის შესაქმნელად. ამასთანავე, ჩვენი ტექნოლოგია უზრუნველყოფს უმაღლესი ხარისხის ვიზუალების გენერირებას, რაც გამორიცხავს ძვირადღირებული ფოტოსესიების საჭიროებას.",
            "ჩვენ ვქმნით ინდივიდუალურ სისტემებს, რომლებიც აერთიანებს გლობალურ გამოცდილებასა და თქვენი ბრენდის უნიკალურ ხმას. ეს უზრუნველყოფს, რომ თითოეული მასალა იყოს მსოფლიო დონის და სრულ შესაბამისობაში მოდიოდეს თანამედროვე სტანდარტებთან, თუმცა იქმნებოდეს 100-ჯერ უფრო სწრაფად."
          ],
          benefits: [
            "თანხის, დროისა და ენერგიის დანაზოგი ვიზუალების შექმნაზე",
            "მუდმივი სოციალური აქტივობა",
            "ტრენდების სწრაფი ათვისება",
            "მსოფლიო დონის ბრენდ-კონსისტენტურობა"
          ],
          features: [
            { title: "პოსტებისა და ბლოგების ავტოპილოტი", desc: "სოციალური ქსელებისა და ვებგვერდისთვის ტექსტური მასალის ავტომატური მომზადება და გამოქვეყნება." },
            { title: "პროდუქტისათვის შექმნილი უმაღლესი ხარისხის ვიზუალები", desc: "ფოტოსებრი ვიზუალების შექმნა სახლიდან გაუსვლელად, რომლებიც რეალობისაგან განურჩეველი იქნება." },
            { title: "თანამედროვე ტრენდებზე მორგებული კონტენტის მუდმივი იდეები", desc: "გლობალური ტრენდების ანალიზი და თქვენს ბრენდზე მორგებული ახალი იდეების მუდმივი მოწოდება." }
          ]
        },
        auto: {
          title: "ბიზნეს ავტომატიზაცია",
          subtitle: "უხილავი სამუშაო პროცესი",
          description: [
            "თუ ერთ მოქმედებას წელიწადში რამდენჯერმე, ან უფრო ხშირად ასრულებთ, მაშინ დიდი ალბათობით მისი ავტომატიზაცია AI-ს საშუალებით არის შესაძლებელი. მომხმარებლებთან ურთიერთობის მენეჯმენტი, დოკუმენტების შექმნა და მონაცემების ამოღება, შიდა ინფორმაციის გაცვლა და ციფრული ინფრასტრუქტურის მოწესრიგება...",
            "ამ და მრავალ სხვა საკითხში ხელოვნურმა ინტელექტმა შესაძლოა ყოველდღიურად საათები დაგიზოგოთ. ჩვენი სისტემები ამ რუტინულ პროცესებს სრულად იღებენ საკუთარ თავზე, რაც საშუალებას მოგცემთ ფოკუსირდეთ ბევრად უფრო მნიშვნელოვან, სტრატეგიულ მიზნებზე და გაზარდოთ ბიზნესის ეფექტურობა."
          ],
          benefits: [
            "საათების დაზოგვა ყოველდღიურად",
            "CRM ავტომატიზაცია",
            "დოკუმენტაციის ავტომატიზაცია",
            "შეცდომებისგან დაცული სისტემა"
          ],
          features: [
            { title: "CRM ავტომატიზაცია", desc: "მომხმარებელთა მონაცემების მართვისა და გაყიდვების პროცესების სრული ავტომატიზაცია ეფექტურობის გასაზრდელად." },
            { title: "დოკუმენტების შექმნა და ინფორმაციის ამოღება", desc: "დოკუმენტაციის გენერირება და ფაილებიდან საჭირო ტექსტური მონაცემების ავტომატური დამუშავება." },
            { title: "ციფრული ინფრასტრუქტურის ავტომატიზაცია", desc: "კომპანიის შიდა სისტემებისა და ხელსაწყოების ერთიანი, ავტომატიზირებული ეკოსისტემის შექმნა." }
          ]
        }
      }
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any; // Returns string or object depending on key
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Helper function to access nested properties by string "nav.services"
  const t = (path: string) => {
    return path.split('.').reduce((obj, key) => obj?.[key], translations[language]) || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};