import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ka';

interface Translations {
  [key: string]: any;
}

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      services: 'Services',
      methodology: 'Methodology',
      whyAi: 'Why AI?',
      cta: 'Schedule a private meeting',
      ctaMobile: 'Schedule Meeting',
      servicesLink: 'Services',
      contactLink: 'Contact',
      privacyLink: 'Privacy Policy',
      copyright: '© 2025 TimeVault Inc. Save your time in the safe space.'
    },
    hero: {
      bgText: 'TIMEVAULT',
      titleLine1: 'The Gap Is Widening',
      titleLine2: 'Be on the right side of history',
      description: 'We are living through the biggest shift since the internet. TimeVault leverages the power of artificial intelligence to build websites, generate content, and automate your entire workflow.',
      cta: 'Explore Solutions',
      stats: {
        saveHours: 'Save Hours everyday',
        increaseRoi: 'Increase ROI',
        boostAwareness: 'Boost Awareness',
        pullAway: 'Pull Away from Competition'
      }
    },
    tools: {
      headline: 'Comprehensive Digital',
      headlineHighlight: 'Acceleration',
      buttons: {
        web: 'Web Architecture',
        content: 'AI Marketing',
        auto: 'Business Automation'
      },
      featured: 'Featured Service',
      exploreBtn: 'Explore',
      content: {
        web: {
          title: "High-Performance Digital Flagships",
          description: "Websites that sell, not just sit. We build lightning-fast, SEO-optimized digital experiences designed to convert visitors into buyers instantly."
        },
        auto: {
          title: "The Invisible Workflow",
          description: "If you are repeating a task, you are wasting money. We implement custom automations that handle the boring, repetitive work in the background."
        },
        content: {
          title: "Infinite Creativity, Zero Burnout",
          description: "Maintain a dominant presence. We generate high-quality blogs, social posts, and ad copy at scale."
        }
      }
    },
    home: {
      rocket: {
        ready: "READY FOR TAKEOFF"
      },
      ecosystem: {
        titleLine1: "Innovation",
        titleLine2: "Without Risk",
        subtitle: "Save your time in the safe space.",
        desc: "Technology is moving fast. Businesses that ignore these tools are becoming obsolete. TimeVault acts as your secure bridge to the future—providing the safety of a managed service with the explosive power of modern AI."
      }
    },
    showcase: {
      tag: "The Visual Turing Test",
      titleLine1: "Don't believe in the",
      titleLine2: "Power of AI?",
      desc: "Many business owners believe AI content still looks robotic or fake. We challenge you to a quick 3-question test. Can your eye distinguish reality from code?",
      cta: "Take the One-Minute Test",
      playing: {
        instruction: "Click the image you think is AI-generated.",
        q1: "Round 1: Select the AI-generated portrait.",
        q2: "Round 2: Which product shot is synthetic?",
        q3: "Round 3: Which interior design never existed?",
        hover: "Pick This One"
      },
      results: {
        tag: "Test Results",
        accuracy: "Total Accuracy",
        messagePart1: "\"Technically, you were right. But the truth is, ",
        messageHighlight: "every single image",
        messagePart2: " you just saw in this test was generated by AI.\"",
        rightSideTitle1: "The Uncanny Valley",
        rightSideTitle2: "Has Been Bridged.",
        rightSideP1: "The bottleneck of quality no longer exists. The era where AI content looked \"fake\" is over. Today, we can generate hyper-realistic assets for your brand at a fraction of the cost and 100x the speed of traditional production.",
        rightSideP2: "This is not just a parlor trick—it is the new economic reality. Businesses that integrate these capabilities now will define the market standards of tomorrow.",
        restart: "Review Images Again"
      }
    },
    footer: {
      brandDesc: "Empowering brands to master time and unlock wealth through intelligent AI automation and high-end design.",
      strategyTitle: "Signature Strategy",
      strategyHighlight: "Engineered for Performance",
      strategyDesc: "Move past standard industry practices. We architect custom frameworks that transform bottlenecks into competitive advantages.",
      ctaButton: "Schedule a Private Meeting",
      ctaSub: "Free Strategy Audit • No Commitment"
    },
    servicePage: {
      backHome: "Back to Home",
      whyChoose: "Why Choose TimeVault?",
      schedule: "Schedule Consultation",
      riskFree: "Risk Free • No Commitment",
      keyCapabilities: "Key Capabilities",
      services: {
        web: {
          title: "Web Architecture",
          subtitle: "High-Performance Digital Flagships",
          description: [
            "In the digital age, your website is your headquarters. Most businesses settle for templates that are slow, insecure, and indistinguishable from their competitors. We don't build websites; we build revenue engines.",
            "Our architecture is headless, meaning the frontend is decoupled from the backend. This results in millisecond load times, bank-grade security, and an experience that feels like a native application rather than a static page."
          ],
          benefits: [
            "Sub-100ms Load Times",
            "Headless CMS Integration (Sanity, Contentful)",
            "Interactive 3D Elements (Three.js, R3F)",
            "Automated SEO Technical Infrastructure"
          ],
          features: [
            { title: "Global CDN", desc: "Your site lives on the edge, deployed to 35+ regions simultaneously." },
            { title: "Conversion Engineering", desc: "Layouts designed by behavioral psychologists to maximize click-through rates." },
            { title: "Dynamic Personalization", desc: "Content that adapts based on the user's location, source, and behavior." }
          ]
        },
        content: {
          title: "AI Marketing",
          subtitle: "Infinite Creativity, Zero Burnout",
          description: [
            "Content is king, but consistency is the kingdom. The biggest challenge for modern brands is maintaining a high volume of quality content across all channels. Humans get tired; our AI engines do not.",
            "We build custom Large Language Models (LLMs) trained specifically on your brand's voice, past successes, and industry terminology. This ensures every piece of content—from tweets to whitepapers—sounds exactly like you, but produced at 100x the speed."
          ],
          benefits: [
            "24/7 Content Production",
            "Brand Voice Consistency Checkers",
            "Multi-Channel Distribution Automation",
            "Trend-Jacking Algorithms"
          ],
          features: [
            { title: "Blog Autopilot", desc: "SEO-rich articles generated, formatted, and posted automatically." },
            { title: "Social Swarm", desc: "One core idea turned into 50+ unique posts for LinkedIn, X, and Instagram." },
            { title: "Visual Synthesis", desc: "AI image generation for thumbnails and ad creatives that stop the scroll." }
          ]
        },
        auto: {
          title: "Business Automation",
          subtitle: "The Invisible Workflow",
          description: [
            "If you are clicking the same button more than once a day, you are losing money. Operational inefficiency is the silent killer of profitability. We build 'invisible' software layers that connect your apps and handle the grunt work.",
            "From client onboarding to invoice reconciliation, our systems listen for triggers and execute complex workflows without human intervention. This frees your team to focus on high-leverage creative and strategic work."
          ],
          benefits: [
            "Eliminate Manual Data Entry",
            "Zero-Error Rate in Routine Tasks",
            "Instant Customer Response Times",
            "Scalable Without Hiring"
          ],
          features: [
            { title: "CRM Sync", desc: "Keep HubSpot, Salesforce, and your Email tools in perfect harmony." },
            { title: "Auto-Invoicing", desc: "Trigger invoices and follow-ups based on project milestones." },
            { title: "Smart Notifications", desc: "Get alerted only when human judgment is actually required." }
          ]
        }
      }
    }
  },
  ka: {
    nav: {
      services: 'სერვისები',
      methodology: 'მეთოდოლოგია',
      whyAi: 'რატომ AI?',
      cta: 'პირადი შეხვედრის დაჯავშნა',
      ctaMobile: 'შეხვედრის დაჯავშნა',
      servicesLink: 'სერვისები',
      contactLink: 'კონტაქტი',
      privacyLink: 'კონფიდენციალურობა',
      copyright: '© 2025 TimeVault Inc. დაზოგეთ დრო უსაფრთხო სივრცეში.'
    },
    hero: {
      bgText: 'TIMEVAULT',
      titleLine1: 'ჩამორჩენა იზრდება',
      titleLine2: 'დადექით ისტორიის სწორ მხარეს',
      description: 'ჩვენ ვცხოვრობთ ყველაზე დიდი ცვლილების ეპოქაში ინტერნეტის შექმნის შემდეგ. TimeVault იყენებს ხელოვნური ინტელექტის ძალას ვებ-გვერდების შესაქმნელად, კონტენტის გენერირებისთვის და თქვენი სამუშაო პროცესის სრული ავტომატიზაციისთვის.',
      cta: 'გაეცანით სერვისებს',
      stats: {
        saveHours: 'დაზოგეთ საათები ყოველდღიურად',
        increaseRoi: 'გაზარდეთ ROI',
        boostAwareness: 'გაზარდეთ ცნობადობა',
        pullAway: 'გაუსწარით კონკურენციას'
      }
    },
    tools: {
      headline: 'ციფრული პროცესების',
      headlineHighlight: 'აქსელერაცია',
      buttons: {
        web: 'ვებ არქიტექტურა',
        content: 'AI მარკეტინგი',
        auto: 'ბიზნეს ავტომატიზაცია'
      },
      featured: 'რჩეული სერვისი',
      exploreBtn: 'აღმოაჩინე',
      content: {
        web: {
          title: "მაღალი წარმადობის ციფრული ფლაგმანები",
          description: "ვებ-გვერდები, რომლებიც ყიდიან და არ არიან უბრალო სავიზიტო ბარათები. ჩვენ ვქმნით სწრაფ, SEO-ოპტიმიზირებულ ციფრულ გამოცდილებას, რომელიც ვიზიტორებს მყისიერად აქცევს მყიდველებად."
        },
        auto: {
          title: "უხილავი სამუშაო პროცესი",
          description: "თუ თქვენ ერთსა და იმავე დავალებას იმეორებთ, თქვენ კარგავთ ფულს. ჩვენ ვნერგავთ ავტომატიზაციას, რომელიც მოსაწყენ, განმეორებად სამუშაოს ფონურ რეჟიმში ასრულებს."
        },
        content: {
          title: "უსაზღვრო კრეატიულობა, გადაწვის გარეშე",
          description: "შეინარჩუნეთ დომინანტური პოზიცია. ჩვენ მასშტაბურად ვქმნით მაღალი ხარისხის ბლოგებს, პოსტებს სოციალური ქსელებისთვის და სარეკლამო ტექსტებს."
        }
      }
    },
    home: {
      rocket: {
        ready: "მზად ვართ აფრენისთვის"
      },
      ecosystem: {
        titleLine1: "ინოვაცია",
        titleLine2: "რისკის გარეშე",
        subtitle: "დაზოგეთ დრო უსაფრთხო სივრცეში.",
        desc: "ტექნოლოგიები სწრაფად ვითარდება. ბიზნესები, რომლებიც ამ ინსტრუმენტებს უგულებელყოფენ, მოძველდებიან. TimeVault არის თქვენი უსაფრთხო ხიდი მომავლისკენ — ჩვენ გთავაზობთ მართვადი სერვისის უსაფრთხოებას თანამედროვე AI-ის ასაფეთქებელ ძალასთან ერთად."
      }
    },
    showcase: {
      tag: "ვიზუალური ტიურინგის ტესტი",
      titleLine1: "არ გჯერათ",
      titleLine2: "AI-ის ძალის?",
      desc: "ბევრ ბიზნეს მფლობელს ჰგონია, რომ AI კონტენტი კვლავ რობოტულად ან ყალბად გამოიყურება. ჩვენ გიწვევთ სწრაფ 3-კითხვიან ტესტზე. შეუძლია თქვენს თვალს გაარჩიოს რეალობა კოდისგან?",
      cta: "გაიარეთ ერთწუთიანი ტესტი",
      playing: {
        instruction: "დააჭირეთ ფოტოს, რომელიც თქვენი აზრით AI-ის შექმნილია.",
        q1: "რაუნდი 1: აირჩიეთ AI-ის მიერ შექმნილი პორტრეტი.",
        q2: "რაუნდი 2: რომელი პროდუქტის ფოტოა სინთეტიკური?",
        q3: "რაუნდი 3: რომელი ინტერიერის დიზაინი არ არსებობდა არასდროს?",
        hover: "აირჩიე ეს"
      },
      results: {
        tag: "ტესტის შედეგები",
        accuracy: "სრული სიზუსტე",
        messagePart1: "\"ტექნიკურად, თქვენ მართალი იყავით. მაგრამ სიმართლე ის არის, რომ ",
        messageHighlight: "თითოეული სურათი",
        messagePart2: ", რომელიც ახლა ნახეთ, AI-ის მიერ იყო გენერირებული.\"",
        rightSideTitle1: "ზღვარი რეალობასა და",
        rightSideTitle2: "გამოგონილს შორის წაიშალა.",
        rightSideP1: "ხარისხის პრობლემა აღარ არსებობს. ეპოქა, როდესაც AI კონტენტი \"ყალბად\" გამოიყურებოდა, დასრულდა. დღეს ჩვენ შეგვიძლია შევქმნათ ჰიპერ-რეალისტური მასალები თქვენი ბრენდისთვის ტრადიციული წარმოების ღირებულების მცირე ნაწილად და 100-ჯერ უფრო სწრაფად.",
        rightSideP2: "ეს არ არის უბრალო გასართობი ტრიუკი — ეს ახალი ეკონომიკური რეალობაა. ბიზნესები, რომლებიც ამ შესაძლებლობებს ახლა დანერგავენ, განსაზღვრავენ ხვალინდელი ბაზრის სტანდარტებს.",
        restart: "სურათების ხელახლა ნახვა"
      }
    },
    footer: {
      brandDesc: "ბრენდების გაძლიერება დროის მართვისა და სიმდიდრის დაგროვების მიზნით, ინტელექტუალური AI ავტომატიზაციისა და მაღალი დონის დიზაინის მეშვეობით.",
      strategyTitle: "უნიკალური სტრატეგია",
      strategyHighlight: "შექმნილია შედეგისთვის",
      strategyDesc: "გასცდით სტანდარტულ ინდუსტრიულ პრაქტიკას. ჩვენ ვქმნით ინდივიდუალურ სისტემებს, რომლებიც შეფერხებებს კონკურენტულ უპირატესობად აქცევს.",
      ctaButton: "პირადი შეხვედრის დაჯავშნა",
      ctaSub: "უფასო სტრატეგიული აუდიტი • ვალდებულებების გარეშე"
    },
    servicePage: {
      backHome: "მთავარზე დაბრუნება",
      whyChoose: "რატომ TimeVault?",
      schedule: "კონსულტაციის დაჯავშნა",
      riskFree: "რისკის გარეშე • ვალდებულებების გარეშე",
      keyCapabilities: "ძირითადი შესაძლებლობები",
      services: {
        web: {
          title: "ვებ არქიტექტურა",
          subtitle: "მაღალი წარმადობის ციფრული ფლაგმანები",
          description: [
            "ციფრულ ეპოქაში თქვენი ვებ-გვერდი თქვენი მთავარი ოფისია. ბიზნესების უმეტესობა კმაყოფილდება შაბლონებით, რომლებიც არის ნელი, დაუცველი და არ განსხვავდება კონკურენტებისგან. ჩვენ არ ვაშენებთ ვებ-გვერდებს; ჩვენ ვაშენებთ შემოსავლის ძრავებს.",
            "ჩვენი არქიტექტურა არის \"Headless\", რაც ნიშნავს, რომ ვიზუალური მხარე გამოყოფილია სერვერისგან. შედეგად ვიღებთ მილიწამიანი ჩატვირთვის დროს, საბანკო დონის უსაფრთხოებას და გამოცდილებას, რომელიც ჰგავს აპლიკაციას და არა სტატიკურ გვერდს."
          ],
          benefits: [
            "100მწ-ზე ნაკლები ჩატვირთვის დრო",
            "Headless CMS ინტეგრაცია (Sanity, Contentful)",
            "ინტერაქტიული 3D ელემენტები (Three.js, R3F)",
            "ავტომატიზირებული SEO ინფრასტრუქტურა"
          ],
          features: [
            { title: "გლობალური CDN", desc: "თქვენი საიტი განთავსებულია 35+ რეგიონში ერთდროულად." },
            { title: "კონვერსიის ინჟინერია", desc: "ქცევითი ფსიქოლოგების მიერ შექმნილი განლაგება დაწკაპუნების მაქსიმიზაციისთვის." },
            { title: "დინამიური პერსონალიზაცია", desc: "კონტენტი, რომელიც ადაპტირდება მომხმარებლის ლოკაციის, წყაროსა და ქცევის მიხედვით." }
          ]
        },
        content: {
          title: "AI მარკეტინგი",
          subtitle: "უსაზღვრო კრეატიულობა, გადაწვის გარეშე",
          description: [
            "კონტენტი მეფეა, მაგრამ სტაბილურობა სამეფოა. თანამედროვე ბრენდების ყველაზე დიდი გამოწვევა მაღალი ხარისხის კონტენტის დიდი მოცულობით წარმოებაა. ადამიანები იღლებიან; ჩვენი AI ძრავები - არა.",
            "ჩვენ ვქმნით ინდივიდუალურ დიდ ენობრივ მოდელებს (LLMs), რომლებიც გაწვრთნილია კონკრეტულად თქვენი ბრენდის ხმაზე, წარსულ წარმატებებსა და ინდუსტრიის ტერმინოლოგიაზე. ეს უზრუნველყოფს, რომ თითოეული მასალა ჟღერდეს ზუსტად ისე, როგორც თქვენ, ოღონდ 100-ჯერ უფრო სწრაფად."
          ],
          benefits: [
            "24/7 კონტენტის წარმოება",
            "ბრენდის ხმის კონსისტენტურობის შემოწმება",
            "მრავალარხიანი დისტრიბუციის ავტომატიზაცია",
            "ტრენდების ალგორითმული ანალიზი"
          ],
          features: [
            { title: "ბლოგის ავტოპილოტი", desc: "SEO-ზე მორგებული სტატიების ავტომატური გენერირება, ფორმატირება და გამოქვეყნება." },
            { title: "Social Swarm", desc: "ერთი იდეის გარდაქმნა 50+ უნიკალურ პოსტად LinkedIn-ისთვის, X-ისა და Instagram-ისთვის." },
            { title: "ვიზუალური სინთეზი", desc: "AI სურათების გენერაცია რეკლამებისთვის, რომლებიც მომხმარებლის ყურადღებას იპყრობს." }
          ]
        },
        auto: {
          title: "ბიზნეს ავტომატიზაცია",
          subtitle: "უხილავი სამუშაო პროცესი",
          description: [
            "თუ თქვენ ერთ ღილაკს დღეში ერთხელ მაინც აჭერთ, თქვენ ფულს კარგავთ. ოპერაციული არაეფექტურობა მომგებიანობის ჩუმი მკვლელია. ჩვენ ვქმნით \"უხილავ\" პროგრამულ შრეებს, რომლებიც აკავშირებენ თქვენს აპლიკაციებს და ასრულებენ შავ სამუშაოს.",
            "კლიენტის რეგისტრაციიდან დაწყებული, ინვოისების შედარებით დამთავრებული, ჩვენი სისტემები ასრულებენ რთულ სამუშაოებს ადამიანის ჩარევის გარეშე. ეს ათავისუფლებს თქვენს გუნდს, რათა ფოკუსირდნენ კრეატიულ და სტრატეგიულ სამუშაოზე."
          ],
          benefits: [
            "მონაცემთა მექანიკური შეყვანის აღმოფხვრა",
            "ნულოვანი შეცდომის მაჩვენებელი",
            "მომხმარებელზე მყისიერი რეაგირება",
            "მასშტაბირება დაქირავების გარეშე"
          ],
          features: [
            { title: "CRM სინქრონიზაცია", desc: "HubSpot, Salesforce და თქვენი იმეილის სრულ ჰარმონიაში მუშაობა." },
            { title: "ავტო-ინვოისინგი", desc: "ინვოისებისა და შეხსენებების გაგზავნა პროექტის ეტაპების მიხედვით." },
            { title: "ჭკვიანი შეტყობინებები", desc: "მიიღეთ შეტყობინება მხოლოდ მაშინ, როცა ადამიანური განსჯა ნამდვილად საჭიროა." }
          ]
        }
      }
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any; // Returns string or object depending on key
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Helper function to access nested properties by string "nav.services"
  const t = (path: string) => {
    return path.split('.').reduce((obj, key) => obj?.[key], translations[language]) || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};